# This workflow will deploy source code on Cloud Run when a commit is pushed to
# the "main" branch.
#
# To configure this workflow:
#
# 1. Enable the following Google Cloud APIs:
#
#    - Artifact Registry (artifactregistry.googleapis.com)
#    - Cloud Build (cloudbuild.googleapis.com)
#    - Cloud Run (run.googleapis.com)
#    - IAM Credentials API (iamcredentials.googleapis.com)
#
#    You can learn more about enabling APIs at
#    https://support.google.com/googleapi/answer/6158841.
#
# 2. Create and configure a Workload Identity Provider for GitHub:
#    https://github.com/google-github-actions/auth#preferred-direct-workload-identity-federation.
#
#    Depending on how you authenticate, you will need to grant an IAM principal
#    permissions on Google Cloud:
#
#    - Artifact Registry Administrator (roles/artifactregistry.admin)
#    - Cloud Run Source Developer (roles/run.sourceDeveloper)
#
#    You can learn more about setting IAM permissions at
#    https://cloud.google.com/iam/docs/manage-access-other-resources.
#
# 3. Change the values in the "env" block to match your values.

name: 'Deploy Function to Cloud Run from Source'

on:
  workflow_call:
    inputs:
      function_dir:
        required: true
        type: string
      function_name:
        required: true
        type: string

env:
  PROJECT_ID: 'copper-oven-434008-v1' # TODO: update to your Google Cloud project ID
  REGION: 'europe-west2' # TODO: update to your region

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Read Configuration'
        id: 'read-config'
        run: |
          CONFIG_FILE="${{ inputs.function_dir }}config.json"
          if [ -f "$CONFIG_FILE" ]; then
            MEMORY=$(jq -r '.memory' $CONFIG_FILE)
            CPU=$(jq -r '.cpu' $CONFIG_FILE)
            TIMEOUT=$(jq -r '.timeout' $CONFIG_FILE)
            RUNTIME=$(jq -r '.runtime' $CONFIG_FILE)
            echo "memory=$MEMORY" >> $GITHUB_OUTPUT
            echo "cpu=$CPU" >> $GITHUB_OUTPUT
            echo "timeout=$TIMEOUT" >> $GITHUB_OUTPUT
            echo "runtime=$RUNTIME" >> $GITHUB_OUTPUT
          else
            echo "Configuration file $CONFIG_FILE not found."
            exit 1
          fi

      # Configure Workload Identity Federation and generate an access token.
      #
      # See https://github.com/google-github-actions/auth for more options,
      # including authenticating via a JSON credentials file.
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_CREDS }}'

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ inputs.function_name }}'
          region: '${{ env.REGION }}'
          # NOTE: If using a different source folder, update the image name below:
          source: '${{ inputs.function_dir }}'
          # memory: '${{ steps.read-config.outputs.memory }}'
          # cpu: '${{ steps.read-config.outputs.cpu }}'
          # timeout: '${{ steps.read-config.outputs.timeout }}'
          # runtime: '${{ steps.read-config.outputs.runtime }}'

      # If required, use the Cloud Run URL output in later steps
      - name: 'Show output'
        run: |-
          echo ${{ steps.deploy.outputs.url }}
