name: 'Deploy Function to Cloud Run from Source 2'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'cloud_functions/**'

env:
  PROJECT_ID: 'copper-oven-434008-v1' # TODO: update to your Google Cloud project ID
  REGION: 'europe-west2' # TODO: update to your region

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Read Configuration'
        id: 'read-config'
        run: |
          CONFIG_FILE="cloud_functions/cloud_function_1/config.json"
          if [ -f "$CONFIG_FILE" ]; then
            MEMORY=$(jq -r '.memory' $CONFIG_FILE)
            CPU=$(jq -r '.cpu' $CONFIG_FILE)
            TIMEOUT=$(jq -r '.timeout' $CONFIG_FILE)
            RUNTIME=$(jq -r '.runtime' $CONFIG_FILE)
            echo "memory=$MEMORY" >> $GITHUB_OUTPUT
            echo "cpu=$CPU" >> $GITHUB_OUTPUT
            echo "timeout=$TIMEOUT" >> $GITHUB_OUTPUT
            echo "runtime=$RUNTIME" >> $GITHUB_OUTPUT
          else
            echo "Configuration file $CONFIG_FILE not found."
            exit 1
          fi

      # Configure Workload Identity Federation and generate an access token.
      #
      # See https://github.com/google-github-actions/auth for more options,
      # including authenticating via a JSON credentials file.
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_CREDS }}'

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'cloud-function-1'
          region: '${{ env.REGION }}'
          # NOTE: If using a different source folder, update the image name below:
          source: '/cloud_functions/cloud_function_1'

      # If required, use the Cloud Run URL output in later steps
      - name: 'Show output'
        run: |-
          echo ${{ steps.deploy.outputs.url }}
